cart/urls.py
from django.urls import patch
from . import views

app_name = 'cart'
urlpatterns = path('add_to_cart/',views.CartItemCreateView.as_view(), name='add_to_cart')

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.main, name='main'),
    path(
        'category/<int:category_id>', 
        views.category_products,
        name='category_products'
    ),
    path(
        '<slug:slug>/',
        views.ProductDetailView.as_view(),
        name='product-detail'
    ),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cart.urls', namespace='cart')),
    path('', include('custom_auth.urls', namespace='auth')),
    path('', include('main.urls', namespace='main')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

main/models.py
from django.db import models

from django.core.validators import MaxValueValidator

from . import mixins

from pytils.translit import slugify


def upload_to(instance, filename:str) -> str:
    '''
    получаем путь для загрузки изображения
    instance: объект Category или ProductImage
    filename: имя загружаемого файла
    '''
    if  isinstance(instance, Category):
        return '/'.join(['categories', instance.name, filename])
    if isinstance(instance, ProductImage):
        return '/'.join(['products', product.category.name, product.name, filename])


class Category(mixins.ActiveMixin):
    name = models.CharField(
        max_length=30,
        null=False,
        blank=False,
        verbose_name='Название категории'
    )
    image = models.ImageField (
        upload_to='category',
        null=True,
        verbose_name='Изображение категории'
    )

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def _str__(self) -> str:
        return self.name


class Product(mixins.ActiveMixin):
    slug = models.SlugField(
        verbose_name='Слаг',
        default='',
        max_length=50,
        unique=True
    )
    name = models.CharField(
        max_length=30,
        null=False,
        blank=False,
        verbose_name='Название категории'
        )
    category = models.ForeignKey(
        to=Category,
        verbose_name='Категория товара',
        on_delete=models.SET_DEFAULT,
        default=None,
        null=True
    )
    price = models.DecimalField(
        verbose_name='Цена товара',
        max_digits=9,
        decimal_places=2,
        default=0
    )
    discount_percent = models.PositiveSmallIntegerField(
        verbose_name='Скидка в процентах',
        null=True,
        default=None,
        validators=[MaxValueValidator(100)]
    )
    count = models.PositiveIntegerField(
        verbose_name='Остаток',
        default=0,
        blank=False
    )

    class Meta: #запрещена в рф
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

    def __str__(self) -> str:
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(f'{self.pk}{self.name}')[:50]
        super().save(*args, **kwargs)

    @property
    def price_with_discount(self):
        if self.discount_percent > 0:
            return self.price - (self.price * self.discount_percent / 100)
        return self.price



class ProductImage(models.Model):
    image = models.ImageField(
        upload_to='product',
        null=True,
        verbose_name='Изображение товара'
    )
    product = models.ForeignKey(
        to=Product,
        verbose_name='Товар',
        null=True,
        on_delete=models.CASCADE
    )

main/views.py
from django.shortcuts import render
from django.views.generic.detail import DetailView

from .models import Category, Product


def main(request):
    categories = Category.objects.filter(is_active=True)
    context = {
        'categories': categories
    }
    return render(request, 'main/main.html', context)


def category_products(request, category_id: int):
    '''
    страница товаров для категории
    '''
    products = Product.objects.filter(category_id=category_id)
    context = {
        'products': products
    }
    return render(request, 'main/product/list.html', context)


class ProductDetailView(DetailView):
    model = Product
    template_name = 'main/product/detail.html'
    context_object_name = 'product'

main/templates/main/product/detail.html
{% extends "base.html" %}
{% load custom_filters %}
{% block content %}
    <h1 class="page-title">{{ product.name }}</h1>
    <div class="product-detail">
        <div class="product-detail__gallery gallery">
            <div class="gallery__item gallery__item_current">
                <img 
                src="{{ product.product_images.first.image.url }}" 
                alt="{{ product.name }}" 
                class="gallery__img"
                >
            </div>
            <div class="gallery__previews">
                {% for img in product.product_images.all %}
                <div 
                class="gallery__preview {% if forloop.counter == 1 %}gallery__preview_active{% endif %}"
                >
                <img 
                src="{{ img.image.url }}" 
                alt="{{ product.name }}" 
                class="gallery__img"
                >
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="product-detail__info">
            <div class="product-detail__description">
                Далеко-далеко за словесными горами в стране гласных и согласных живут рыбные тексты. Своих над грустный безорфографичный. Обеспечивает жизни переписывается за безорфографичный журчит проектах повстречался использовало пунктуация. Родного.
            </div>
            <div class="product-detail__price">
                {{ product.price|price }}
            </div>
        </div>
    </div>
{% endblock %}

main/templates/main/product/list.html
{% extends "base.html" %}
{% load static %}
{% load custom_filters %}
{% block title %}{{ category.name }}{% endblock %}
{% block content %}
    <h1 class="page-title">{{ category.name }}</h1>
    <div class="products">
        {% for product in products %}
            <a class="products__item product" href="{% url 'main:product-detail' slug=product.slug %}">
                {% if product.discount_percent > 0 %}
                    <div class="product__discount">
                        -{{ product.discount_percent }}%
                    </div>
                {% endif %}
                <div class="product__img-wrapper">
                    <img
                            class="product__img"
                            src="{{ product.product_images.all.0.image.url }}"
                            alt="{{ product.name }}"
                    >
                </div>
                <div class="product__name">
                    {{ product.name }}
                </div>
                <div class="product__price">
                    {{ product.price|price }}
                </div>
                <button data-id="{{ product.id }}" data-url="{% url 'cart:add_to_cart' %}" class="product__add">
                    в корзину срочно
                </button>
            </a>
        {% endfor %}
    </div>
{% endblock %}