cart/urls.py
from django.urls import patch
from . import views

app_name = 'cart'
urlpatterns = path('add_to_cart/',views.CartItemCreateView.as_view(), name='add_to_cart')

custom_auth/urls.py
from django.urls import path

from . import views

app_name = 'auth'

urlpatterns = [
    path('register/', views.user_register, name='register'),
    path('verify/<str:email>/<str:activation_code>', views.verify_user, name='verify'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.logout_views, name= 'logout'),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cart.urls', namespace='cart')),
    path('', include('custom_auth.urls', namespace='auth')),
    path('', include('main.urls', namespace='main')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

templates/includes/footer.html
<footer class="footer"></footer>

templates/includes/header.html
{% load static %}
<header class="header">
    <div class="container">
        <div class="header__content">
            <a href="/" class="header__logo" title="Главная">
                <img src="{% static 'img/logo.png' %}" alt="Интернет магазин" class="header__logo-img">
            </a>
            <form action="" class="search">
                <input type="text" class="search__input" placeholder="Имя товара">
                <button type="submit" class="search__btn" title="Поиск">
                    <img src="{% static 'img/search.svg' %}" alt="">
                </button>
            </form>
            <nav class="nav">
                <menu class="menu">
                    {% if request.user.is_anonymous %}
                    <div class="menu__item">
                        <a href="{% url 'auth:login' %}" class="menu__link">Вход</a>
                    </div>
                    <div class="menu__item">
                        <a href="{% url 'auth:register' %}" class="menu__link">Регистрация</a>
                    </div>
                    {% else %}
                        <div class="menu__item">
                            <a href="#" class="menu__link">{{ request.user.email }}</a>
                        </div>
                        <div class="menu__item">
                            <a href="{% url 'auth:logout' %}" class="menu__link">Выход</a>
                        </div>
                    </div>
                    {% endif %}
                </menu>
            </nav>
            <a href="#" class="header__cart" title="Корзина">
                <img src="{% static 'img/cart.svg' %}" alt="" class="cart__icon">
                <div class="cart__count">{{ cart_count }}</div>
            </a>
        </div>
    </div>
</header>